language: go

os:
- linux
- osx

go:
- "1.13"

git:
  depth: 3

go_import_path: sigs.k8s.io/application

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
-

script:
# enable golangci-lint check when the code is migrated to kubebuilder v2.0, which is a simplified version
#- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
#- golangci-lint run --enable=gofmt --enable=goimports --enable=unparam --enable=nakedret
- make test

# TBD. Suppressing for now.
notifications:
  email: false