apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "test-application-01"
  labels:
    app.kubernetes.io/name: "test-01"
spec:
  type: "test"
  selector:
    matchLabels:
      app.kubernetes.io/name: "test-01"
  componentKinds:
  - group: apps
    kind: Deployment
  - group: batch
    kind: Job
  - group: v1
    kind: Service
  - group: v1
    kind: ConfigMap
  - group: test.crd.com
    kind: TestCRD
  addOwnerRef: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-hello
  labels:
    app.kubernetes.io/name: "test-01"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "hello-world"
    app.kubernetes.io/tier: "backend"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "test-01"
      app.kubernetes.io/component: "hello-world"
      app.kubernetes.io/tier: "backend"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "test-01"
        app.kubernetes.io/component: "hello-world"
        app.kubernetes.io/tier: "backend"
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  labels:
    app.kubernetes.io/name: "test-01"
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: Service
metadata:
  name: test-webserver-svc
  labels:
    app.kubernetes.io/name: "test-01"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "test-svc"
    app.kubernetes.io/tier: "frontend"
spec:
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: "test-01"
    app.kubernetes.io/component: "test-webserver"
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  labels:
    app.kubernetes.io/name: "test-01"
data:
  data-1: value-1
  data-2: value-2
---
apiVersion: test.crd.com/v1
kind: TestCRD
metadata:
  name: testcrd-sample
  labels:
    app.kubernetes.io/name: "test-01"
spec:
  foo: bar
---
apiVersion: test.crd.com/v1
kind: TestCRD
metadata:
  name: testcrd-sample-2
  labels:
    app.kubernetes.io/name: "test-01"
spec:
  foo: bar
---
apiVersion: test.crd.com/v1
kind: TestCRD
metadata:
  name: testcrd-sample-3
  labels:
    app.kubernetes.io/name: "test-01"
spec:
  foo: bar
